function [methodinfo,structs,enuminfo]=MySharedDLL;
%MYSHAREDDLL Create structures to define interfaces found in 'MySharedDLL'.

%This function was generated by loadlibrary.m parser version 1.1.6.20.4.1 on Thu Dec 23 13:03:35 2010
%perl options:'MySharedDLL.i -outfile=MySharedDLL.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
structs=[];enuminfo=[];fcnNum=1;
%  VOID SetSharedMem ( char * lpszBuf ); 
fcns.name{fcnNum}='SetSharedMem'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  VOID GetSharedMem ( char * lpszBuf , DWORD cchSize ); 
fcns.name{fcnNum}='GetSharedMem'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}={'cstring', 'uint32'};fcnNum=fcnNum+1;
%  VOID setReadIndex ( int index ); 
fcns.name{fcnNum}='setReadIndex'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
%  VOID setWriteIndex ( int index ); 
fcns.name{fcnNum}='setWriteIndex'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
%  int getReadIndex ( void ); 
fcns.name{fcnNum}='getReadIndex'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  VOID setReadIndex_to_testvalue ( void ); 
fcns.name{fcnNum}='setReadIndex_to_testvalue'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int getWriteIndex ( void ); 
fcns.name{fcnNum}='getWriteIndex'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  VOID setIndexedDataPacket ( double * Packet , int index ); 
fcns.name{fcnNum}='setIndexedDataPacket'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='error'; fcns.RHS{fcnNum}={'doublePtr', 'int32'};fcnNum=fcnNum+1;
%  double * getIndexedDataPacket ( double * Packet , int index ); 
fcns.name{fcnNum}='getIndexedDataPacket'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='doublePtr'; fcns.RHS{fcnNum}={'doublePtr', 'int32'};fcnNum=fcnNum+1;
%  double * getLastWrittenDataPacket ( double * Packet ); 
fcns.name{fcnNum}='getLastWrittenDataPacket'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='doublePtr'; fcns.RHS{fcnNum}={'doublePtr'};fcnNum=fcnNum+1;
%  int setNextDataPacket ( double * Packet ); 
fcns.name{fcnNum}='setNextDataPacket'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'doublePtr'};fcnNum=fcnNum+1;
%  int getPacketWidth ( void ); 
fcns.name{fcnNum}='getPacketWidth'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int getNumOfPacketsInBuffer ( void ); 
fcns.name{fcnNum}='getNumOfPacketsInBuffer'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int getPacketBSize ( void ); 
fcns.name{fcnNum}='getPacketBSize'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  double * getIndexedDataBlock ( double * Packets , int start_index , int end_index ); 
fcns.name{fcnNum}='getIndexedDataBlock'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='doublePtr'; fcns.RHS{fcnNum}={'doublePtr', 'int32', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;